// SPDX-License-Identifier: BSD-3-Clause
/* Copyright (c) 2023, Danila Tikhonov <danila@jiaxyga.com> */

#include <sys/mman.h>
#include <err.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "debugcc.h"

static struct debug_mux cam_cc = {
	.phys = 0xad00000,
	.size = 0x10000,
	.block_name = "cam",

	.enable_reg = 0xd008,
	.enable_mask = BIT(0),

	.mux_reg = 0xd000,
	.mux_mask = 0xff,

	.div_reg = 0xd004,
	.div_mask = 0xf,
	.div_val = 4,
};

static struct debug_mux cpu_cc = {
	.phys = 0x182a0000,
	.size = 0x1000,
	.block_name = "cpu",

	.enable_reg = 0x18,
	.enable_mask = BIT(0),

	.mux_reg = 0x18,
	.mux_mask = 0x7f << 4,
	.mux_shift = 4,

	.div_reg = 0x18,
	.div_mask = 0xf << 11,
	.div_shift = 11,
	.div_val = 1,
};)

static struct debug_mux disp_cc = {
	.phys = 0xaf00000,
	.size = 0x20000,
	.block_name = "disp",

	.enable_reg = 0x500c,
	.enable_mask = BIT(0),

	.mux_reg = 0x7000,
	.mux_mask = 0xff,

	.div_reg = 0x5008,
	.div_mask = 0x3,
	.div_val = 4,
};

static struct debug_mux gcc = {
	.phys = 0x100000,
	.size = 0x1f0000,

	.enable_reg = 0x62004,
	.enable_mask = BIT(0),

	.mux_reg = 0x62008,
	.mux_mask = 0x3ff,

	.div_reg = 0x62004,
	.div_mask = 0xf,
	.div_val = 1,

	.xo_div4_reg = 0x43008,
	.debug_ctl_reg = 0x62024,
	.debug_status_reg = 0x62028,
};

static struct debug_mux gpu_cc = {
	.phys = 0x5090000,
	.size = 0x9000,
	.block_name = "gpu",

	.enable_reg = 0x1100,
	.enable_mask = BIT(0),

	.mux_reg = 0x1568,
	.mux_mask = 0xff,

	.div_reg = 0x10fc,
	.div_mask = 0x3,
	.div_val = 2,
};

static struct debug_mux mc_cc = {
	.phys =	0x90b0000,
	.size = 0x1000,
	.block_name = "mc",

	.measure = measure_mccc,
};

static struct debug_mux npu_cc = {
	.phys = 0x9910000,
	.size = 0x10000,
	.block_name = "npu",

	.enable_reg = 0x3008,
	.enable_mask = BIT(0),

	.mux_reg = 0x4000,
	.mux_mask = 0xff,

	.div_reg = 0x3004,
	.div_mask = 0x3,
	.div_val = 2,
};

static struct debug_mux video_cc = {
	.phys = 0xab00000,
	.size = 0x10000,
	.block_name = "video",

	.enable_reg = 0x940,
	.enable_mask = BIT(0),

	.mux_reg = 0xacc,
	.mux_mask = 0x3f,

	.div_reg = 0x938,
	.div_mask = 0x7,
	.div_val = 5,
};

static struct measure_clk sm7150_clocks[] = {
	{ "cam_cc_bps_ahb_clk", &gcc, 0x46, &cam_cc, 0xe },
	{ "cam_cc_bps_areg_clk", &gcc, 0x46, &cam_cc, 0xd },
	{ "cam_cc_bps_axi_clk", &gcc, 0x46, &cam_cc, 0xc },
	{ "cam_cc_bps_clk", &gcc, 0x46, &cam_cc, 0xb },
	{ "cam_cc_camnoc_axi_clk", &gcc, 0x46, &cam_cc, 0x27 },
	{ "cam_cc_camnoc_dcd_xo_clk", &gcc, 0x46, &cam_cc, 0x33 },
	{ "cam_cc_cci_0_clk", &gcc, 0x46, &cam_cc, 0x2a },
	{ "cam_cc_cci_1_clk", &gcc, 0x46, &cam_cc, 0x3b },
	{ "cam_cc_core_ahb_clk", &gcc, 0x46, &cam_cc, 0x2e },
	{ "cam_cc_cpas_ahb_clk", &gcc, 0x46, &cam_cc, 0x2c },
	{ "cam_cc_csi0phytimer_clk", &gcc, 0x46, &cam_cc, 0x5 },
	{ "cam_cc_csi1phytimer_clk", &gcc, 0x46, &cam_cc, 0x7 },
	{ "cam_cc_csi2phytimer_clk", &gcc, 0x46, &cam_cc, 0x9 },
	{ "cam_cc_csi3phytimer_clk", &gcc, 0x46, &cam_cc, 0x35 },
	{ "cam_cc_csiphy0_clk", &gcc, 0x46, &cam_cc, 0x6 },
	{ "cam_cc_csiphy1_clk", &gcc, 0x46, &cam_cc, 0x8 },
	{ "cam_cc_csiphy2_clk", &gcc, 0x46, &cam_cc, 0xa },
	{ "cam_cc_csiphy3_clk", &gcc, 0x46, &cam_cc, 0x36 },
	{ "cam_cc_fd_core_clk", &gcc, 0x46, &cam_cc, 0x28 },
	{ "cam_cc_fd_core_uar_clk", &gcc, 0x46, &cam_cc, 0x29 },
	{ "cam_cc_gdsc_clk", &gcc, 0x46, &cam_cc, 0x3c },
	{ "cam_cc_icp_ahb_clk", &gcc, 0x46, &cam_cc, 0x37 },
	{ "cam_cc_icp_clk", &gcc, 0x46, &cam_cc, 0x26 },
	{ "cam_cc_ife_0_axi_clk", &gcc, 0x46, &cam_cc, 0x1b },
	{ "cam_cc_ife_0_clk", &gcc, 0x46, &cam_cc, 0x17 },
	{ "cam_cc_ife_0_cphy_rx_clk", &gcc, 0x46, &cam_cc, 0x1a },
	{ "cam_cc_ife_0_csid_clk", &gcc, 0x46, &cam_cc, 0x19 },
	{ "cam_cc_ife_0_dsp_clk", &gcc, 0x46, &cam_cc, 0x18 },
	{ "cam_cc_ife_1_axi_clk", &gcc, 0x46, &cam_cc, 0x21 },
	{ "cam_cc_ife_1_clk", &gcc, 0x46, &cam_cc, 0x1d },
	{ "cam_cc_ife_1_cphy_rx_clk", &gcc, 0x46, &cam_cc, 0x20 },
	{ "cam_cc_ife_1_csid_clk", &gcc, 0x46, &cam_cc, 0x1f },
	{ "cam_cc_ife_1_dsp_clk", &gcc, 0x46, &cam_cc, 0x1e },
	{ "cam_cc_ife_lite_clk", &gcc, 0x46, &cam_cc, 0x22 },
	{ "cam_cc_ife_lite_cphy_rx_clk", &gcc, 0x46, &cam_cc, 0x24 },
	{ "cam_cc_ife_lite_csid_clk", &gcc, 0x46, &cam_cc, 0x23 },
	{ "cam_cc_ipe_0_ahb_clk", &gcc, 0x46, &cam_cc, 0x12 },
	{ "cam_cc_ipe_0_areg_clk", &gcc, 0x46, &cam_cc, 0x11 },
	{ "cam_cc_ipe_0_axi_clk", &gcc, 0x46, &cam_cc, 0x10 },
	{ "cam_cc_ipe_0_clk", &gcc, 0x46, &cam_cc, 0xf },
	{ "cam_cc_ipe_1_ahb_clk", &gcc, 0x46, &cam_cc, 0x16 },
	{ "cam_cc_ipe_1_areg_clk", &gcc, 0x46, &cam_cc, 0x15 },
	{ "cam_cc_ipe_1_axi_clk", &gcc, 0x46, &cam_cc, 0x14 },
	{ "cam_cc_ipe_1_clk", &gcc, 0x46, &cam_cc, 0x13 },
	{ "cam_cc_jpeg_clk", &gcc, 0x46, &cam_cc, 0x25 },
	{ "cam_cc_lrme_clk", &gcc, 0x46, &cam_cc, 0x2b },
	{ "cam_cc_mclk0_clk", &gcc, 0x46, &cam_cc, 0x1 },
	{ "cam_cc_mclk1_clk", &gcc, 0x46, &cam_cc, 0x2 },
	{ "cam_cc_mclk2_clk", &gcc, 0x46, &cam_cc, 0x3 },
	{ "cam_cc_mclk3_clk", &gcc, 0x46, &cam_cc, 0x4 },
	{ "cam_cc_sleep_clk", &gcc, 0x46, &cam_cc, 0x3f },

	{ "disp_cc_mdss_ahb_clk", &gcc, 0x47, &disp_cc, 0x1f },
	{ "disp_cc_mdss_byte0_clk", &gcc, 0x47, &disp_cc, 0x13 },
	{ "disp_cc_mdss_byte0_intf_clk", &gcc, 0x47, &disp_cc, 0x14 },
	{ "disp_cc_mdss_byte1_clk", &gcc, 0x47, &disp_cc, 0x15 },
	{ "disp_cc_mdss_byte1_intf_clk", &gcc, 0x47, &disp_cc, 0x16 },
	{ "disp_cc_mdss_dp_aux_clk", &gcc, 0x47, &disp_cc, 0x1e },
	{ "disp_cc_mdss_dp_crypto_clk", &gcc, 0x47, &disp_cc, 0x1b },
	{ "disp_cc_mdss_dp_link_clk", &gcc, 0x47, &disp_cc, 0x19 },
	{ "disp_cc_mdss_dp_link_intf_clk", &gcc, 0x47, &disp_cc, 0x1a },
	{ "disp_cc_mdss_dp_pixel1_clk", &gcc, 0x47, &disp_cc, 0x1d },
	{ "disp_cc_mdss_dp_pixel_clk", &gcc, 0x47, &disp_cc, 0x1c },
	{ "disp_cc_mdss_esc0_clk", &gcc, 0x47, &disp_cc, 0x17 },
	{ "disp_cc_mdss_esc1_clk", &gcc, 0x47, &disp_cc, 0x18 },
	{ "disp_cc_mdss_mdp_clk", &gcc, 0x47, &disp_cc, 0xf },
	{ "disp_cc_mdss_mdp_lut_clk", &gcc, 0x47, &disp_cc, 0x11 },
	{ "disp_cc_mdss_non_gdsc_ahb_clk", &gcc, 0x47, &disp_cc, 0x20 },
	{ "disp_cc_mdss_pclk0_clk", &gcc, 0x47, &disp_cc, 0xd },
	{ "disp_cc_mdss_pclk1_clk", &gcc, 0x47, &disp_cc, 0xe },
	{ "disp_cc_mdss_rot_clk", &gcc, 0x47, &disp_cc, 0x10 },
	{ "disp_cc_mdss_rscc_ahb_clk", &gcc, 0x47, &disp_cc, 0x22 },
	{ "disp_cc_mdss_rscc_vsync_clk", &gcc, 0x47, &disp_cc, 0x21 },
	{ "disp_cc_mdss_vsync_clk", &gcc, 0x47, &disp_cc, 0x12 },
	{ "disp_cc_xo_clk", &gcc, 0x47, &disp_cc, 0x2a },

	{ "gcc_aggre_noc_pcie_tbu_clk", &gcc, 0x2d },
	{ "gcc_aggre_ufs_phy_axi_clk", &gcc, 0x11d },
	{ "gcc_aggre_usb3_prim_axi_clk", &gcc, 0x11b },
	{ "gcc_apc_vs_clk", &gcc, 0x113 },
	{ "gcc_boot_rom_ahb_clk", &gcc, 0x94 },
	{ "gcc_camera_ahb_clk", &gcc, 0x3a },
	{ "gcc_camera_hf_axi_clk", &gcc, 0x40 },
	{ "gcc_camera_sf_axi_clk", &gcc, 0x176 },
	{ "gcc_camera_xo_clk", &gcc, 0x43 },
	{ "gcc_ce1_ahb_clk", &gcc, 0xa9 },
	{ "gcc_ce1_axi_clk", &gcc, 0xa8 },
	{ "gcc_ce1_clk", &gcc, 0xa7 },
	{ "gcc_cfg_noc_usb3_prim_axi_clk", &gcc, 0x1d },
	{ "gcc_cpuss_ahb_clk", &gcc, 0xce },
	{ "gcc_cpuss_gnoc_clk", &gcc, 0xcf },
	{ "gcc_cpuss_rbcpr_clk", &gcc, 0xd0 },
	{ "gcc_ddrss_gpu_axi_clk", &gcc, 0xbb },
	{ "gcc_disp_ahb_clk", &gcc, 0x3b },
	{ "gcc_disp_gpll0_clk_src", &gcc, 0x4c },,
	{ "gcc_disp_gpll0_div_clk_src", &gcc, 0x4d },
	{ "gcc_disp_hf_axi_clk", &gcc, 0x41 },
	{ "gcc_disp_sf_axi_clk", &gcc, 0x177 },
	{ "gcc_disp_xo_clk", &gcc, 0x44 },
	{ "gcc_gp1_clk", &gcc, 0xde },
	{ "gcc_gp2_clk", &gcc, 0xdf },
	{ "gcc_gp3_clk", &gcc, 0xe0 },
	{ "gcc_gpu_cfg_ahb_clk", &gcc, 0x142 },
	{ "gcc_gpu_gpll0_clk_src", &gcc, 0x148 },
	{ "gcc_gpu_gpll0_div_clk_src", &gcc, 0x149 },
	{ "gcc_gpu_memnoc_gfx_clk", &gcc, 0x145 },
	{ "gcc_gpu_snoc_dvm_gfx_clk", &gcc, 0x147 },
	{ "gcc_gpu_vs_clk", &gcc, 0x112 },
	{ "gcc_npu_axi_clk", &gcc, 0x16a },
	{ "gcc_npu_cfg_ahb_clk", &gcc, 0x169 },
	{ "gcc_npu_gpll0_clk_src", &gcc, 0x16d },
	{ "gcc_npu_gpll0_div_clk_src", &gcc, 0x16e },
	{ "gcc_pcie_0_aux_clk", &gcc, 0xe5 },
	{ "gcc_pcie_0_cfg_ahb_clk", &gcc, 0xe4 },
	{ "gcc_pcie_0_mstr_axi_clk", &gcc, 0xe3 },
	{ "gcc_pcie_0_pipe_clk", &gcc, 0xe6 },
	{ "gcc_pcie_0_slv_axi_clk", &gcc, 0xe2 },
	{ "gcc_pcie_0_slv_q2a_axi_clk", &gcc, 0xe1 },
	{ "gcc_pcie_phy_aux_clk", &gcc, 0xef },
	{ "gcc_pcie_phy_refgen_clk", &gcc, 0x160 },
	{ "gcc_pdm2_clk", &gcc, 0x8e },
	{ "gcc_pdm_ahb_clk", &gcc, 0x8c },
	{ "gcc_pdm_xo4_clk", &gcc, 0x8d },
	{ "gcc_prng_ahb_clk", &gcc, 0x8f },
	{ "gcc_qupv3_wrap0_core_2x_clk", &gcc, 0x77 },
	{ "gcc_qupv3_wrap0_core_clk", &gcc, 0x76 },
	{ "gcc_qupv3_wrap0_s0_clk", &gcc, 0x78 },
	{ "gcc_qupv3_wrap0_s1_clk", &gcc, 0x79 },
	{ "gcc_qupv3_wrap0_s2_clk", &gcc, 0x7a },
	{ "gcc_qupv3_wrap0_s3_clk", &gcc, 0x7b },
	{ "gcc_qupv3_wrap0_s4_clk", &gcc, 0x7c },
	{ "gcc_qupv3_wrap0_s5_clk", &gcc, 0x7d },
	{ "gcc_qupv3_wrap0_s6_clk", &gcc, 0x7e },
	{ "gcc_qupv3_wrap0_s7_clk", &gcc, 0x7f },
	{ "gcc_qupv3_wrap1_core_2x_clk", &gcc, 0x80 },
	{ "gcc_qupv3_wrap1_core_clk", &gcc, 0x81 },
	{ "gcc_qupv3_wrap1_s0_clk", &gcc, 0x84 },
	{ "gcc_qupv3_wrap1_s1_clk", &gcc, 0x85 },
	{ "gcc_qupv3_wrap1_s2_clk", &gcc, 0x86 },
	{ "gcc_qupv3_wrap1_s3_clk", &gcc, 0x87 },
	{ "gcc_qupv3_wrap1_s4_clk", &gcc, 0x88 },
	{ "gcc_qupv3_wrap1_s5_clk", &gcc, 0x89 },
	{ "gcc_qupv3_wrap1_s6_clk", &gcc, 0x8a },
	{ "gcc_qupv3_wrap1_s7_clk", &gcc, 0x8b },
	{ "gcc_qupv3_wrap_0_m_ahb_clk", &gcc, 0x74 },
	{ "gcc_qupv3_wrap_0_s_ahb_clk", &gcc, 0x75 },
	{ "gcc_qupv3_wrap_1_m_ahb_clk", &gcc, 0x82 },
	{ "gcc_qupv3_wrap_1_s_ahb_clk", &gcc, 0x83 },
	{ "gcc_sdcc1_ahb_clk", &gcc, 0x15c },
	{ "gcc_sdcc1_apps_clk", &gcc, 0x15b },
	{ "gcc_sdcc1_ice_core_clk", &gcc, 0x15d },
	{ "gcc_sdcc2_ahb_clk", &gcc, 0x71 },
	{ "gcc_sdcc2_apps_clk", &gcc, 0x70 },
	{ "gcc_sdcc4_ahb_clk", &gcc, 0x73 },
	{ "gcc_sdcc4_apps_clk", &gcc, 0x72 },
	{ "gcc_sys_noc_cpuss_ahb_clk", &gcc, 0xc },
	{ "gcc_tsif_ahb_clk", &gcc, 0x90 },
	{ "gcc_tsif_inactivity_timers_clk", &gcc, 0x92 },
	{ "gcc_tsif_ref_clk", &gcc, 0x91 },
	{ "gcc_ufs_phy_ahb_clk", &gcc, 0xfc },
	{ "gcc_ufs_phy_axi_clk", &gcc, 0xfb },
	{ "gcc_ufs_phy_ice_core_clk", &gcc, 0x102 },
	{ "gcc_ufs_phy_phy_aux_clk", &gcc, 0x103 },
	{ "gcc_ufs_phy_rx_symbol_0_clk", &gcc, 0xfe },
	{ "gcc_ufs_phy_tx_symbol_0_clk", &gcc, 0xfd },
	{ "gcc_ufs_phy_unipro_core_clk", &gcc, 0x101 },
	{ "gcc_usb30_prim_master_clk", &gcc, 0x5f },
	{ "gcc_usb30_prim_mock_utmi_clk", &gcc, 0x61 },
	{ "gcc_usb30_prim_sleep_clk", &gcc, 0x60 },
	{ "gcc_usb3_prim_phy_aux_clk", &gcc, 0x62 },
	{ "gcc_usb3_prim_phy_com_aux_clk", &gcc, 0x63 },
	{ "gcc_usb3_prim_phy_pipe_clk", &gcc, 0x64 },
	{ "gcc_usb_phy_cfg_ahb2phy_clk", &gcc, 0x6f },
	{ "gcc_vdda_vs_clk", &gcc, 0x10e },
	{ "gcc_vddcx_vs_clk", &gcc, 0x10c },
	{ "gcc_vddmx_vs_clk", &gcc, 0x10d },
	{ "gcc_video_ahb_clk", &gcc, 0x39 },
	{ "gcc_video_axi_clk", &gcc, 0x3f },
	{ "gcc_video_xo_clk", &gcc, 0x42 },
	{ "gcc_vs_ctrl_ahb_clk", &gcc, 0x110 },
	{ "gcc_vs_ctrl_clk", &gcc, 0x10f },

	{ "measure_only_mccc_clk", &gcc, 0xc2 },
	{ "measure_only_cnoc_clk", &gcc, 0x15 },
	{ "measure_only_ipa_2x_clk", &gcc, 0x128 },
	{ "measure_only_snoc_clk", &gcc, 0x7 },

	{ "gpu_cc_acd_ahb_clk", &gcc, 0x144, &gpu_cc, 0x20 },
	{ "gpu_cc_acd_cxo_clk", &gcc, 0x144, &gpu_cc, 0x1f },
	{ "gpu_cc_ahb_clk", &gcc, 0x144, &gpu_cc, 0x11 },
	{ "gpu_cc_crc_ahb_clk", &gcc, 0x144, &gpu_cc, 0x12 },
	{ "gpu_cc_cx_apb_clk", &gcc, 0x144, &gpu_cc, 0x15 },
	{ "gpu_cc_cx_gfx3d_clk", &gcc, 0x144, &gpu_cc, 0x1a },
	{ "gpu_cc_cx_gfx3d_slv_clk", &gcc, 0x144, &gpu_cc, 0x1b },
	{ "gpu_cc_cx_gmu_clk", &gcc, 0x144, &gpu_cc, 0x19 },
	{ "gpu_cc_cx_snoc_dvm_clk", &gcc, 0x144, &gpu_cc, 0x16 },
	{ "gpu_cc_cxo_aon_clk", &gcc, 0x144, &gpu_cc, 0xb },
	{ "gpu_cc_cxo_clk", &gcc, 0x144, &gpu_cc, 0xa },
	{ "gpu_cc_gx_cxo_clk", &gcc, 0x144, &gpu_cc, 0xf },
	{ "gpu_cc_gx_gfx3d_clk", &gcc, 0x144, &gpu_cc, 0xc },
	{ "gpu_cc_gx_gmu_clk", &gcc, 0x144, &gpu_cc, 0x10 },
	{ "gpu_cc_gx_vsense_clk", &gcc, 0x144, &gpu_cc, 0xd },

	{ "npu_cc_armwic_core_clk", &gcc, 0x16f, &npu_cc, 0x4 },
	{ "npu_cc_bto_core_clk", &gcc, 0x16f, &npu_cc, 0x12 },
	{ "npu_cc_bwmon_clk", &gcc, 0x16f, &npu_cc, 0xf },
	{ "npu_cc_cal_dp_cdc_clk", &gcc, 0x16f, &npu_cc, 0x8 },
	{ "npu_cc_cal_dp_clk", &gcc, 0x16f, &npu_cc, 0x1 },
	{ "npu_cc_comp_noc_axi_clk", &gcc, 0x16f, &npu_cc, 0x9 },
	{ "npu_cc_conf_noc_ahb_clk", &gcc, 0x16f, &npu_cc, 0xa },
	{ "npu_cc_npu_core_apb_clk", &gcc, 0x16f, &npu_cc, 0xe },
	{ "npu_cc_npu_core_atb_clk", &gcc, 0x16f, &npu_cc, 0xb },
	{ "npu_cc_npu_core_clk", &gcc, 0x16f, &npu_cc, 0x2 },
	{ "npu_cc_npu_core_cti_clk", &gcc, 0x16f, &npu_cc, 0xc },
	{ "npu_cc_npu_cpc_clk", &gcc, 0x16f, &npu_cc, 0x3 },
	{ "npu_cc_npu_cpc_timer_clk", &gcc, 0x16f, &npu_cc, 0x5 },
	{ "npu_cc_perf_cnt_clk", &gcc, 0x16f, &npu_cc, 0x10 },
	{ "npu_cc_qtimer_core_clk", &gcc, 0x16f, &npu_cc, 0x6 },
	{ "npu_cc_sleep_clk", &gcc, 0x16f, &npu_cc, 0x7 },
	{ "npu_cc_xo_clk", &gcc, 0x16f, &npu_cc, 0x11 },

	{ "video_cc_apb_clk", &gcc, 0x48, &video_cc, 0xe },
	{ "video_cc_at_clk", &gcc, 0x48, &video_cc, 0x11 },
	{ "video_cc_iris_ahb_clk", &gcc, 0x48, &video_cc, 0x7 },
	{ "video_cc_mvs0_axi_clk", &gcc, 0x48, &video_cc, 0xb },
	{ "video_cc_mvs0_core_clk", &gcc, 0x48, &video_cc, 0x3 },
	{ "video_cc_mvs1_axi_clk", &gcc, 0x48, &video_cc, 0xc },
	{ "video_cc_mvs1_core_clk", &gcc, 0x48, &video_cc, 0x5 },
	{ "video_cc_mvsc_core_clk", &gcc, 0x48, &video_cc, 0x1 },
	{ "video_cc_mvsc_ctl_axi_clk", &gcc, 0x48, &video_cc, 0xa },
	{ "video_cc_venus_ahb_clk", &gcc, 0x48, &video_cc, 0xf },
	{ "video_cc_xo_clk", &gcc, 0x48, &video_cc, 0x8 },

	{ "l3_clk", &gcc, 0xd6, &cpu_cc, 0x46, 16 },
	{ "pwrcl_clk", &gcc, 0xd6, &cpu_cc, 0x44, 16 },
	{ "perfcl_clk", &gcc, 0xd6, &cpu_cc, 0x45, 16 },
	{}
};

struct debugcc_platform sm7150_debugcc = {
	"sm7150",
	sm7150_clocks,
};
